// Code generated by goctl. DO NOT EDIT.

export interface Request {
}

export interface RequestParams {
	name: string // parameters are auto validated
}

export interface Response {
	message: string
}

